{% set name = "python-pegasus-wms" %}
{% set version = "4.9.3" %}
{% set sha256 = "7c88018b03990f41c661ea687e583e315308826ba344804817ffd942702d799b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://download.pegasus.isi.edu/pegasus/{{ version }}/pegasus-python-source-{{ version }}.tar.gz
  sha256: 7c88018b03990f41c661ea687e583e315308826ba344804817ffd942702d799b
  patches:
    # loosen requirements
    - requirements.patch
    # remove call to deprecated commands module
    - commands.patch
    # fix indentation
    - indent.patch
    # use configobj release instead of vendored
    - configobj.patch
    # use pamela instead of pam
    - pamela.patch
    # fix use of flask-cache
    - flask-cache.patch

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - boto >=2.48.0
    - configobj
    # flask-cache itself needs flask <1.0.0a0
    - flask >=0.12.4,<1.0.0a0
    - flask-cache >=0.13.1
    - flask-sqlalchemy >=0.16
    - future
    - itsdangerous >=0.24
    - jinja2 >=2.8.1
    - markupsafe >=1.0
    - pamela
    - psycopg2 >=2.6
    - pyopenssl >=17.5.0
    - pyparsing
    - python
    - requests >=2.18.4
    - sqlalchemy >=0.8.0
    - werkzeug >=0.14.1

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - Pegasus.DAX3

about:
  home: https://pegasus.isi.edu
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: This package contains the Python APIs for Pegasus WMS
  description: |
    This package contains the Python APIs for Pegasus WMS, including:

    - The DAX API (Versions 2 and 3)
    - The PDAX API (Version 2)
    - The monitoring API
    - The Stampede database API
    - The Pegasus statistics API
    - The Pegasus plots API
    - Misc. Pegasus utilities

extra:
  recipe-maintainers:
    - duncanmmacleod
