travis:
  secure:
    BINSTAR_TOKEN: LG0cKQw2OkEuBmmTk1MSo9woeXAyyiYywIHkcZf6g3/P6GxCaw6wQvRcMSwlnW/1aN0p8rWM0yUzgF5OKBYDsds6VcJDtLs6oHjlz6Nc7Z+1vt+fLL+wW/ociDr37iVcCsMY6qR3YspmfUX0Z8F9JKXuzXL1MHc5+t81Qkp3Vwkda2hK/g4uqor7jFfT8ln7bjFRn5TVtW9bHO5ZXyGVJk7EXB9VCACXT/VFjHn+cQmsb0xXX+G5vlNC+/TgsT0l7w/ycyAijE0syvncK7GBrxwOkim7P0hUO2jj+DGDdFawB/JpAhOcMHeOvaX9All0rtvmu730tByQlHN8L1iN3UlaS3qnBmCxRTQAQU+/Lkv/xFpN25lS4XGUBN5t/ZjS6DEo1zJZ97VCZw3Qn1Vq3zZ5EpH1dKNSqO1SJuwVRwVoy2vYCQ9h+uHe45T/SxlNNUb38wsf1odQapQN34tgMEZFRj/hxaJmhvmmakc/JgLnt6f/YrIwf88PMnW4WvFghYd5wYZzjARqohJvX1584uvEpU/vn8YFKba5ndWSMKHGHRLU7A2i8D90a3H6Zo4uwLr3d2w0egdxyBSqj3+EHgsF6EGYaxC6JDtY465sAopmK5PkUy/IFvcK+H1meBT7WZLjw9s3KiHIJsBEwv5b73ERvJqSgZV+Ad1/Oub+m/o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
