travis:
  secure:
    BINSTAR_TOKEN: d2c4cCai3nzXdku+9KyAGGKIA2dmmURyFiAW7zGR+gWrCZyD8+udGBSQBALqIvry2ndmrc1wUyN4+LIYEJRVWq3m1D3BrzLPtavWbOD7E1bSl9ha/1BI6jdmNHCsM2CatVI23WsuaECIJtZvECsoMERYe/EiJGheRUnvZcUBcPJW6qCFFOcegJ/Kh5u9RbWMtJmrX6uo/xAD7QwDAcfHZ9r/tWtFhWt40twZZQCgk72zGLnXp1UlA8joApMBQSlpSM8urQfjl7QTBLIfyxnEfXhw9Awo4nU/z/Ein23sEAdjYjYzVy+bU8Tmc2nXfuklOxjyVsu2DaFzZLD2iVauqqqf4PYwdtAXWgv8D8HCLGu+Kgoy/yCohbbtc5LGsFL20A1UIlL/a4oRVIoVeCW4EMvQUoRNqePgqPquz5GDPePxzjxgSNavJ0Csy10hyQk0TwO0v3XWEQShpAM2+wbfhQhvPm7b4CN56eJ5vPqpVnFlL57hpoaUAdP/F27armjJLXBhP78DvMUFUUoJK1Ey3vEg4NcmWbxT8oMYcvLFJF8UwRaXi6KACtPVUKl86PKVK9eAxr25Ar3VtwCLCi+Gm3hwsS+drG1q6SE0pR2/XfVOqSwJBhka28Q2QdXBfaJfqawqiLzsX/65lRzBq1IP9qETHGfx5YIjSiKWLwMPeEk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
