travis:
  secure:
    BINSTAR_TOKEN: U569sGWm/Z1AgivwMnbr53ds4h/mDS5x6IjEtELDbjHXxk09t3yF1HmjvY6Lp31hrfDD2FfJtmkQhTpTZv5StyyPk04bZLyWfErNZLma8ziXAFVtcn7jmR1YXLcomtCnco5yx96yppe0jNapjjqIkn0m2ucGxrOpaW8ZB/MhdKIppLQq94LickBAMEprSRm7FnuCKXdEqJ+91/K/Ykoo8w7oRZilyzHNGVHcF2jp4M+VHt3jcPmwwmvaKyA3AuCJSKwsBILNKFHjOvsTsKw8kyOlTyC/nZLZ20atHyAHtg6Qry+Kba4UQENHrR3px2ZCXUrl/bJ8rZZcYbvlUzDX8wEOVRrTtawSunBpLCvbKgLnds/XmGnmMKLYY6AKU2Atv7f7ga41vmOqN0SL8PJ987NLbWnYzvlmNmMJoyEHvJFCPNzXdFmB1OlR+Z88L/UDQSPebz5NVeIJ3RG/yNxpRUoDXSL3nLqOy9IIcSXwd+oVM5uBwBm0VXr0+FFx3VBT0XvL9fYx3ZzV06tEEe+7X1Rb3EKl7yPRfE/jCu99izTTcvyxTsGQRQtWIJa5zNX0O+kl+BdNDz5+dit8QAD/YxowbnL1X6KFya51FTF0jkgv8L9hEGvKrk9iRxPbtUt8af+maKibQGZsx+aHtIwGj6/LJI4M6yAsNwhUpqAeGCU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
